### ISSUE TITLE
[REFACTOR] [GET] /review/:shopId?sort&offset&limit 테스트코드 작성, 리팩토링

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#100]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- 이런 걸 해야해

## TODO

- [x] 테스트 코드 작성
  - [ ] sort가 like인 경우
  - [ ] sort가 save인 경우
  - [ ] sort가 recent인 경우  
  - [ ] sort가 없는 경우
  - [ ] sort가 지정된 value 이외인 경우
  - [ ] offset과 limit이 정상적인 경우
  - [ ] offset만 온 경우
  - [ ] limit만 온 경우
  - [ ] offset과 limit이 없는 경우
  - [ ] offset이 0 이하인 경우
  - [ ] limit이 0 이하인 경우
  - [ ] offset이 숫자가 아닌 경우
  - [ ] limit이 숫자가 아닌 경우
- [x] 리팩토링
  - [ ] 주석 (필요한 경우)
  - [ ] 효율성 개선
  - [ ] 변수명 개선
  - [ ] orm 살펴보기
