### ISSUE TITLE
[REFACTOR] [GET] /shop/category 테스트코드 작성, 리팩토링

### ISSUE THREAD

**Issue by choiyoorim** [TeamSodam/sodam-server#101]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- 카테고리별 소품샵 리스트 제공 코드 테스트하는 코드 작성
- 카테고리별 소품샵 리스트 제공 코드 리팩토링

## TODO

- [x] 테스트 코드 작성
- [x] 리팩토링
