### ISSUE TITLE
[REFACTOR] [GET] /shop/search?keyword={} 테스트코드 작성, 리팩토링

### ISSUE THREAD

**Issue by choiyoorim** [TeamSodam/sodam-server#103]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- 소품샵 검색 기능 api 리팩토링

## TODO

- [x] [GET] /shop/search?keyword={} 테스트 코드 작성
- [x] [GET] /shop/search?keyword={} 리팩토링
