### ISSUE TITLE
[REFACTOR] [GET] /review/recent 테스트코드 작성, 리팩토링

### ISSUE THREAD

**Issue by choiyoorim** [TeamSodam/sodam-server#105]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- 최근 작성된 리뷰 제공 api 리팩토링

## TODO

- [ ] [GET] /review/recent 테스트 코드 작성
- [ ] [GET] /review/recent 리팩토링
