### ISSUE TITLE
[REFACTOR] [GET] /my/review/scrap 테스트코드 작성, 리팩토링

### ISSUE THREAD

**Issue by choiyoorim** [TeamSodam/sodam-server#109]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- 스크랩한 리뷰 확인 기능 api 리팩토링

## TODO

- [ ] [GET] /my/review/scrap 테스트 코드 작성
- [ ]  [GET] /my/review/scrap 리팩토링
