### ISSUE TITLE
[REFACTOR] [POST] /shop/bookmark 테스트코드 작성, 리팩토링 

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#114]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요
- 테스트 코드 작성
- 리팩토링

## TODO

- [ ] 테스트 코드 작성
- [ ] 리팩토링
