### ISSUE TITLE
[FEATURE] [GET] shop/all 

### ISSUE THREAD

**Issue by Nahee-Park** [TeamSodam/sodam-server#119]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 전체 소품샵 한번에 불러오는 api 개발 (어드민용)

## TODO

- [x] sort 기준 최신순, ㄱㄴㄷ순 구현 
- [x]  page, limit 구현
