### ISSUE TITLE
[FEATURE] get admin/shop/data 

### ISSUE THREAD

**Issue by Nahee-Park** [TeamSodam/sodam-server#123]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

-  어드민에서 확인할 데이터들 한번에 가져오는 api 제작

## TODO

- [x] 전체 소품샵 수 
- [x] 전체 리뷰 수
- [x] 지역별 소품샵 수
- [x] 테마별 소품샵 수
- [x] 소품샵 종류별 소품샵 수
- [x] 필요한 요소들 다 들어갔는지에 대한 테스트 코드 간단히 작성
