### ISSUE TITLE
[FEATURE] 닉네임 중복 체크

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#127]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 닉네임 중복 체크

## TODO

- [x] orm 작성: 입력값과 같은 닉네임 있는지 확인
- [x] 입력값 확인 (최대 10글자)
  - [x] 실패: 닉네임 없음
  - [x] 실패: 10글자 초과
- [x] 성공: 같은 닉네임 있는경우
- [x] 성공: 같은 닉네임 없는 경우
