### ISSUE TITLE
[REFACTOR] 회원가입 폴더구조 및 파일 이름 변경

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#128]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요
- signup 관련 코드를 한 폴더 안에 넣는 것이 목적 
- authSignupPOST.js를 auth/signup 폴더로 옮기고, 파일명을 signupPOST.js로 변경

## TODO

- [x] authSignupPOST.js를 auth/signup 폴더로 옮기고, 파일명을 signupPOST.js로 변경
