### ISSUE TITLE
[FEATURE] 이메일 인증번호 전송 (이메일 중복 체크)

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#129]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 이메일 인증번호 전송 (이메일 중복 체크)

## TODO

- [x] orm: 이메일 중복 체크 (이미 있음)
- [x] email 잘 왔는지 확인
  - [x] fail: 이메일 값 없는 경우
  - [x] fail: 이메일 값이 잘못된 경우
- [x] 이메일 중복 확인
  - [x] success: 가입 불가능한 이메일인 경우
- [x] 메일 전송 로직 실행
- [x] success: 가입 가능한 이메일인 경우
- [ ] 인증번호 저장
