### ISSUE TITLE
[FEATURE] 이메일 인증번호 확인

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#130]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 이런 걸 할거야

## TODO

- [x] 파라미터 확인
  - [x] fail: email 또는 verificationNumber 값이 없는 경우
  - [x] fail: email 값이 잘못된 경우
  - [x] fail: verificationNumber 값이 잘못된 경우
- [ ] 저장된 인증번호 가져오기
- [x] 인증번호 일치 여부 확인
  - [x] success: 인증번호가 일치하지 않는 경우
  - [x] success: 인증번호가 일치하는 경우
