### ISSUE TITLE
[FEATURE] 이미지 업로드 경로 설정 기능

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#131]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 현재 이미지 업로드할 때 전부 original 폴더에 저장됨
- 미들웨어 사용할 때 파라미터로 폴더명을 받고, 해당 폴더에 이미지를 업로드하게 할 예정

## TODO

- [ ] 파라미터로 폴더명 받기
- [ ] 해당 폴더에 업로드하기
