### ISSUE TITLE
[FEATURE] [PUT] 닉네임 수정

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#134]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 닉네임 수정

## TODO

- [ ] orm 작성
- [ ] 파라미터 확인 - 10글자 초과면 fail
- [ ] DB 수정
- [ ] 성공 response
