### ISSUE TITLE
[FEATURE] [PUT] 새로운 프로필 사진 등록

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#135]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 이런 걸 할거야

## TODO

- [ ] orm 작성
- [ ] 프로필 사진 업로드
- [ ] response 보내기
