### ISSUE TITLE
[FEATURE] [PUT] 선호 소품 테마 수정

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#136]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요
- 선호 소품 테마 수정
- 유저-선호 테마 테이블 필요

## TODO
- [ ] 유저 - 선호 테마 테이블 필요
- [ ] orm 작성
- [ ] 파라미터 확인
- [ ] 선호 테마 수정
- [ ] response 보내기
