### ISSUE TITLE
[FEATURE] 현재 프로필 사진 삭제

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#137]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 현재 프로필 사진 삭제

## TODO

- [ ] orm 작성
- [ ] 성공 response 보내기
