### ISSUE TITLE
[FEATURE] 프로필 사진 가져오기

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#139]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- [GET] user/image
- 마이페이지
- 프로필 사진 가져오기

## TODO

- [ ]  orm 작성 (join 이용)
- [ ] 로그인
- [ ]  파라미터 확인
- [ ]  response 보내기
