### ISSUE TITLE
[BUG] shop response에서 image, category가 null 나옴

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#150]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- image, category가 null로 나오는 api들이 있어요.
- 정상적으로 실행되는 api들도 있는 것을 보면, DB 연동 문제는 아닌 듯 합니다.

* image가 null로 나와요
  - shop/boomarkGET
    + GET {{baseUrl}}/shop/bookmark?sort=recent&limit=2&offset=1
  - shopCategoryGET - 소품샵 종류별 소품샵 리스트
    + GET {{baseUrl}}/shop/category?type=문구팬시
  - shop/shopGET 위치별,구별 소품샵 가져오기
    + GET {{baseUrl}}/shop?area=강남구&sort=recent
  - shop/shopGET 소품샵 가져오기(테마별)
    + GET {{baseUrl}}/shop?offset=1&limit=20&sort=poopular&theme=힙한
* category가 null로 나와요
  - shop/boomarkGET
    + GET {{baseUrl}}/shop/bookmark?sort=recent&limit=2&offset=1
  - shop/shopGET 소품샵 가져오기(테마별)
    + GET {{baseUrl}}/shop?offset=1&limit=20&sort=poopular&theme=힙한
  - shop/shopRecommendGET - 소품샵 추천
    + GET {{baseUrl}}/shop/recommend?type=popular
   
## TODO
- [ ] 각자 본인이 작성했던 코드 확인해보기
- [ ] 어떤 브랜치 merge헀을때부터 오류 생겼는지 찾기

**Comment by Nahee-Park** [comment]
@LeeJE20  저 위에 이슈로 걸어둔 api들 전부 수정해서 푸쉬했습니다 ! 제가 지금 배포버전에서 확인한 바로는 다 수정됐는데, 한 번 더 검토한 이후 이슈 닫아도 될 것 같아요

**Comment by LeeJE20** [comment]
저도 검토했는데 괜찮아 보여서 이슈 닫을게요!
