### ISSUE TITLE
[BUG] 이메일 인증번호 response 수정

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#151]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- 이메일 인증번호 부분에서 이미 가입된 이메일을 요청했을때 명세에는 status:200, uniqueEmail : false, “verificationCode”: “” 로 보내주신다고 했는데 실제로는 status:400으로 에러로 옴

## TODO

- [x] 상태코드 200으로 변경
