### ISSUE TITLE
[FIX] 인증코드 이메일 내용 수정

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#154]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- 이메일 인증코드 내용 수정

## TODO

- [ ] 이메일 인증코드 내용 수정
