### ISSUE TITLE
[BUG] review 테스트코드 버그

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#156]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- my/review/write에서 헤더 accesstoken에 값 안 넣으면 오류 발생
- response message에 중복되는 코드 있음

## TODO

- [ ] 버그 수정
- [ ] 중복 코드 삭제
