### ISSUE TITLE
[REFACTOR] shop 테스트 코드의 review 관련 내용 이동

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#157]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- reivew 테스트코드가 shop 테스트코드 파일에 있음

## TODO

- [ ] review 관련 내용은 review 테스트 파일로 옮기기
