### ISSUE TITLE
[BUG] 로그인 api response 오류

### ISSUE THREAD

**Issue by choiyoorim** [TeamSodam/sodam-server#167]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- api 명세서상 로그인 api response에 유저 닉네임도 담겨야하는데 accesstoken만 전달됨

## TODO

- [ ] user 정보로부터 nickname 가져오기
- [ ] 닉네임 response에 담아 전달
