### ISSUE TITLE
[BUG] 회원가입 시 선택한 소품샵 정보 누락

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#169]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- 회원가입 후에 마이페이지 들어가면 회원가입시 선택한 소품샵 정보가 안 옴

## TODO

- [ ] 회원가입 때 받은 선호테마도 userThemePost와 같은 방식으로 넣어주도록 수정
