### ISSUE TITLE
[CHORE] rds, s3 이동

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#171]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- rds, s3 새 계정으로 이동

## TODO

- [ ] rds 생성 및 데이터 넣기
- [ ] s3 생성 및 데이터 넣기
