### ISSUE TITLE
jwt 토큰 생성 함수 로직 수정

### ISSUE THREAD

**Issue by Nahee-Park** [TeamSodam/sodam-server#172]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## BUG 개요

- jwt payload 비번 이슈

## TODO

- [ ]  jwt 핸들러 수정
