### ISSUE TITLE
[chore] 소품샵 더미 이미지 진짜 이미지로 변경

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#174]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 지금 이미지 더미 디비로 연결되어 있는 것 진짜 이미지 디비로 옮기기 -> 없는 소품샵에 대해 이미지 삽입, 이미지가 없습니다 이미지 디비에 넣기
- image_test_table2에 일단  크롤링 한 이미지들 저장되어 있고, 소담 구글 드라이브에 이미지 없는 소품샵정보랑, 해당 소품샵에 대한 이미지 기획이 정리해서 넣어둔 게 있음

## TODO
- [ ] 더미 이미지 진짜 이미지로 변경
