### ISSUE TITLE
[FEATURE] 어드민페이지 소품샵 등록 api 제작 

### ISSUE THREAD

**Issue by choiyoorim** [TeamSodam/sodam-server#175]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 어드민 페이지에서 소품샵을 쉽게 등록하거나 소품샵 정보를 수정할 수 있도록 하는 api 제작

## TODO

- [ ] 어드민 권한 확인 후 처리
- [ ] 소품샵 정보 등록 or 수정 분기처리
- [ ] 소품샵 정보 저장 
- [ ] 소품샵 이미지 저장시 파일 혹은 링크로도 저장 가능하게끔 처리
