### ISSUE TITLE
[BUG] 홈 화면 - 오늘의 소품샵 리뷰 - 정렬 안 됨

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#191]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## BUG 개요

- 노션 QA 테스트(기획) 참고
- 리뷰가 최신순으로 있는 게 아니고 랜덤으로 있는 것 같음, 날이 섞여 있음

## TODO

- [ ] 리뷰 최신순으로 정렬
