### ISSUE TITLE
[BUG] 소품샵 리뷰 필터 오동작

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#192]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- 리뷰 필터링이 제대로 안 되어 있음
- 소품샵 상세 페이지, 리뷰 상세 페이지
- ~/review/:shopId?sort={}&offset={}&limit={}

## TODO

- [ ] getReviewByShopIdOrderBySort에서 쿼리 수정
`ORDER BY r.${order} DESC, r.created_at DESC, r.id`
