### ISSUE TITLE
[REFACTOR] [POST] /admin/shop/newshop 테스트코드 작성, 리팩토링

### ISSUE THREAD

**Issue by choiyoorim** [TeamSodam/sodam-server#198]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- 새로운 소품샵 등록 api 테스트 코드 작성 

## TODO

- [ ] [POST] /admin/shop/newshop 테스트 코드 작성
- [ ] [POST] /admin/shop/newshop 오류 해결 및 리팩토링
