### ISSUE TITLE
[FEATURE] 어드민 소품샵 삭제 기능 추가

### ISSUE THREAD

**Issue by choiyoorim** [TeamSodam/sodam-server#199]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 어드민 페이지에서 소품샵 삭제 기능을 구현

## TODO

- [ ] 특정 소품샵 아이디값 넘어오면 해당 소품샵 삭제
