### ISSUE TITLE
[FEATURE] 초기세팅 

### ISSUE THREAD

**Issue by Nahee-Park** [TeamSodam/sodam-server#2]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 초기세팅 하기 

## TODO

- [x] aws ec2 인스턴스 파기
- [x] aws rds 파기
- [x] ec2에 깃 레포지토리 연결하고 필요한 모듈 설치 
- [x] 폴더구조 세팅 
- [x] ci/cd 스크립트 작성하기
