### ISSUE TITLE
[FEATURE] [GET] /shop/:shopId/location

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#20]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 이런 걸 할거야

## TODO

- [x] 새로운 브랜치 만들기
- [x] 라우팅 경로 설정
- [x] constants 작성
- [x] API 기본 틀 작성
- [x] ORM 작성
    + [x] db 라우팅 파일 작성 (shop) 
    + [x] 샵 id에 해당하는 샵 정보 가져오기
    + [x] 지하철역에 해당하는 샵 정보 가져오기 ORDER BY bookmark, like, id LIMIT 20
- [x] API 내용 작성
    - [x] params
      + [x] shopId 없으면 fail
    - [x] db 요청해서 shopId에 해당하는 지하철역 정보 얻기
    - [x] db 요청: 지하철역에 해당하는 샵 정보 20개 얻기
    - [x] response 보내기
