### ISSUE TITLE
[FIX] db script 테이블 형식에 맞게 수정

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#201]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- db 스크립트 테이블 형식에 맞게 수정

## TODO

- [ ] user 테이블에서 preference theme 관련 column 삭제
