### ISSUE TITLE
[BUG] 소품샵 추천 - 랜덤 

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#202]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## BUG 개요
- shop/recommend?type=random
- 현재 구현 상황
  - 예를 들어 소품샵 개수가 433개라 합시다.
  - 1~433 까지의 정수 중 랜덤으로 20개 고르고, 각 숫자와 소품샵 id가 같은 소품샵을 가져옵니다.
- 발생 가능한 문제
  - admin에서 기존의 소품샵을 delete하는 기능이 추가됩니다.
  - 랜덤 넘버가 [1~소품샵 개수] 만큼의 경우의 수 안에서 발생하므로, delete된 소품샵에 대해 읽기 요청이 발생할 수도 있습니다.
  - 예를 들어 5번 소품샵을 삭제했는데, 랜덤넘버가 5가 나온다면 소품샵을 가져올 때 에러가 발생할 것입니다.

## TODO

- [ ] delete된 소품샵을 불러오지 않도록 수정이 필요합니다.
  - 상황이 급하면 다음과 같은 쿼리를 활용해도 좋을 듯 합니다. random()에 따라 전체 정렬을 하므로 성능이 좋은 방식은 아니지만, 현재 소품샵 개수가 많은 상황이 아니므로 응답속도가 못 쓸 정도로 느리지는 않습니다.
  ```sql
  --- 랜덤으로 소품샵 선택
  SELECT *
  FROM shop
  WHERE is_deleted = false
  ORDER BY random()
  LIMIT 20;
  ```
