### ISSUE TITLE
[FEATURE] [GET] /shop/recommend?type

### ISSUE THREAD

**Issue by choiyoorim** [TeamSodam/sodam-server#23]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 이런 걸 할거야

## TODO

- [ ] 토큰 유무에 따라 다르게 나타내야 함
- [x] 쿼리 따라서 다르게 줘야 함(랜덤 및 추천순)
- [x] 내용 적절하게 웹으로 전달
