### ISSUE TITLE
[FEATURE] [GET] shop/:shopId/review/:reviewId api 제작

### ISSUE THREAD

**Issue by Nahee-Park** [TeamSodam/sodam-server#25]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

-  [GET] shop/:shopId/review/:reviewId 

## TODO

- [ ] apif 라우팅 개발 
- [ ] db로직 개발
