### ISSUE TITLE
[REFACTOR] 소품샵 상세페이지 리뷰 sort 분기처리 수정

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#26]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

이 부분 그냥 sort값을 쿼리문으로 보내고 쿼리문에서 명령어를 분기처리한다면 코드양이 훨씬 줄어들 수 있을 것 같아요!

_Originally posted by @Nahee-Park in https://github.com/TeamSodam/sodam-server/pull/19#discussion_r785428721_

## TODO

- [ ]  sort값을 쿼리문으로 보내기
- [ ] 쿼리문에서 명령어를 분기처리
- [ ] API 로직 수정
