### ISSUE TITLE
[FIX] 소품샵 상세페이지 리뷰 수정

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#27]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요
- [GET] /review/:shopId?sort=&offset=&limit= 으로 수정
- 클라단에서 페이지네이션 쿼리를 `?offset={}&limit={}`으로 통일해주기로 함
- 현재 ?page={}로 구현되어있음
- response 유저 부분 writerName, writerThumbnail으로 바꾸기

_Originally posted by @Nahee-Park in https://github.com/TeamSodam/sodam-server/pull/19#discussion_r785425872_

## TODO

- [x] query 받는 부분 고치기
- [x] API 로직 변경 (offset, limit 부분)
- [x] response 유저 부분 바꾸기 (sql을 바꾸기)
