### ISSUE TITLE
[FEATURE] [GET] /shop/category?type api 제작

### ISSUE THREAD

**Issue by choiyoorim** [TeamSodam/sodam-server#29]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 카테고리별 랜덤으로 소품샵을 추천해주는 api 제작

## TODO

- [x] 카테고리별 쿼리문 제작
- [x] 카테고리별로 랜덤 추출
- [x] 데이터 넘겨주기
