### ISSUE TITLE
[FEATURE] ㅇㅇㅇapi 제작 

### ISSUE THREAD

**Issue by Nahee-Park** [TeamSodam/sodam-server#3]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 로그인 api 짜기

## TODO

- [x] api 제작
- [x] db 로직 짜기 
- [ ] jwt 공부하기 
- [ ] Xxx 해보자
