### ISSUE TITLE
[FEATURE] [POST] /shop/bookmark

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#34]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 소품샵 저장 API 개발

## TODO
- [x] 새로운 브랜치 만들기
- [x] 라우팅 경로 설정
- [x] constants 작성
- [x] API 기본 틀 작성
- [x] ORM 작성
    + [x] db 라우팅 파일 작성 (shop) 
    + [x] 샵 id, user id에 해당하는 북마크 정보 가져오기 (id, is_deleted)
    + [x] create new bookmark (by user id, shop id)
    + [x] update bookmark (by user id, shop id, isBookmarked) - isBookmarked와 반대가 되게 is_deleted 업데이트 
    + [x] update bookmark count of **shop table**, **bookmark_count** 컬럼- 파라미터로 +1 또는 -1 받기 
- [x] API 내용 작성
    - [x] req.body 체크 - 없으면 response fail 400
    - [x] 로그인 체크 - 없으면  response fail 
    - [x] user id, shop id에 해당하는 북마크 정보(id, is deleted) 가져오기
    - [x] 북마크 없으면 db 요청: 북마크 정보 만들기
    - [x] db 요청: 북마크 정보 isBookmarked대로 업데이트하기
    - [x] toSum 변수: 북마크 수 몇을 더해야 하는지 계산하기 (+1 또는 -1) 
      + [x] isBookmarked: True, is_deleted: True: +1
      + [x] 둘이 같으면 0 (isBookmarked: True, is_deleted: False: 0 && isBookmarked: False, is_deleted: False: 0)
      + [x] isBookmarked: False, is_deleted: True: - 1
    - [x] toSum이 0이 아닐때 db 요청: 리뷰 테이블 북마크 수 업데이트하기 
    - [x] response 보내기
