### ISSUE TITLE
[FEATURE] [GET] /shop/search?keyword api 제작

### ISSUE THREAD

**Issue by choiyoorim** [TeamSodam/sodam-server#36]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요
- 소품샵을 검색했을 때 해당 소품샵에 대한 정보를 제공하는 기능 

## TODO

- [ ] keyword값 쿼리로 받기
- [ ] 키워드를 이용한 데이터 검색
- [ ] 데이터 넘겨주기
