### ISSUE TITLE
[FEATURE] [POST] /auth/signup, /auth/login

### ISSUE THREAD

**Issue by Nahee-Park** [TeamSodam/sodam-server#41]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [ㅌ] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- [POST] /auth/signup 개발
- [POST] /auth/login 개발

## TODO

- [x] 회원가입 로직 개발
- [x] 토큰 생성 로직 개발
- [x] 토큰 검증 로직 개발
- [ ] 중복 이메일 점검 로직 개발
- [ ] 비밀번호 암호화 로직 추가
- [x] 로그인 로직 개발
- [ ] checkUser 미들웨어 구현
