### ISSUE TITLE
[FEATURE] [GET] my/review/scrap

### ISSUE THREAD

**Issue by choiyoorim** [TeamSodam/sodam-server#42]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 내가 스크랩한 리뷰 목록 가져오는 기능

## TODO

- [ ] 내가 스크랩한 리뷰라는 데이터 조건 설정
- [ ] 해당 데이터 보내주기
