### ISSUE TITLE
[FEATURE] user, review item, tag,image 더미데이터 넣는 스크립트 작성

### ISSUE THREAD

**Issue by Nahee-Park** [TeamSodam/sodam-server#44]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

-  user, review item, tag,image 더미데이터 넣는 스크립트 작성

## TODO

- [ ] 현재 db에 임시로 들어가 있는 더미데이터 삭제, 정리
- 더미데이터 넣는 스크립트 작성
- [x] user테이블
- [x] tag 테이블
- [x] review 테이블
- [x] review_tag 테이블
- [x] review_item 테이블
- [x] review_image 테이블
