### ISSUE TITLE
[FIX] [GET] /shop/:shopId 로그인

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#47]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요
- develop 브랜치에서 작업
- 로그인 추가
- response

## TODO

-  [x] 로그인 확인 미들웨어 붙이기
-  [x] 로그인 했다면 북마크 여부 가져오기 (로그인 안하면 false)
- [x] response 에서 id를 shopId로 바꾸기
