### ISSUE TITLE
[REFACTOR] 소품샵 마이리뷰 checkuser 붙이기 

### ISSUE THREAD

**Issue by choiyoorim** [TeamSodam/sodam-server#50]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- 이런 걸 해야해

## TODO

- [x] 작성자가 스크랩한 리뷰 목록 확인하는 api에 checkuser 미들웨어 붙이기
- [x] 작성자가 작성한 리뷰 목록 확인하는 api에 checkuser 미들웨어 붙이기
