### ISSUE TITLE
[FEATURE] DB에 이미지 저장

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#54]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요
- s3에 이미지 올리고 url 받아와서 소품샵 대표이미지로 저장

## TODO

- [x] s3에 이미지 올리는 api 만들기
- [x] script에 이미지 배열 저장
- [x] script로 DB에 이미지 저장
