### ISSUE TITLE
[FEATURE] [GET] /shop/?area api 제작

### ISSUE THREAD

**Issue by Nahee-Park** [TeamSodam/sodam-server#6]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

-  [GET] /shop/?area api 제작

## TODO

- [x] 위치 기반 소품샵 GET api 개발
- [x] db 로직 개발
- [x] 데이터 가공  공통 유틸 만들기 
- [x] 유틸 기반으로 클라에게 보내줄 데이터 가공 
- [x] 페이지네이션 구현
