### ISSUE TITLE
[BUG]  해당 소품샵 리뷰 - response 데이터 수정

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#61]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요
- /review/:shopId?sort=&offset={}&limit={}
- response body writerThumnail 배열로 나옴
- res에서 리뷰가 없을 때도 리뷰카운트 안 나옴
- 파일: reviewShopIdSortPageGET.js

## TODO

- [x] writerThumnail 일반 string으로 고치기
- [x] 리뷰가 없을 때 리뷰카운트 넣기

**Comment by Nahee-Park** [comment]
@LeeJE20  src/routes/review/reviewShopIdSortPageGET.js 파일 지금도 리뷰카운트 안 나오고 있는 상태인가요 ?

**Comment by LeeJE20** [comment]
리뷰 있을 때는 리뷰카운트 나오는데 리뷰 없을 때 리뷰카운트 안 나와요 (아예 key 자체가 없어요)

**Comment by LeeJE20** [comment]
> @LeeJE20 src/routes/review/reviewShopIdSortPageGET.js 파일 지금도 리뷰카운트 안 나오고 있는 상태인가요 ?
@Nahee-Park 
리뷰 있을 때는 리뷰카운트 나오는데 리뷰 없을 때 리뷰카운트 안 나와요 (아예 key 자체가 없어요)
