### ISSUE TITLE
[Bug] 내가 작성한 리뷰 response 수정 요망

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#64]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요
- response 데이터 필요한 칼럼이 없음
- shopId, shopName, category 추가
- response 메시지 없음

## TODO

- [ ] response: shopId, shopName, category 추가
- [ ] response 메시지 추가
- [ ] API 문서 수정
