### ISSUE TITLE
[BUG] 내가 작성한 리뷰 제대로 안 불러와짐 

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#67]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- 내가 작성한 리뷰가 제대로 안 불러와짐
- my/myReviewGET.js

- {{baseUrl}}/my/review/write로 요청보내는 다음 오류 생김 (토큰은 1번 유저)
  - 다른 리뷰가 선택됨 -> 원인: 유저 아이디로 리뷰를 선택해야 하는데 리뷰 아이디로 선택중임
  - 첫 번쨰 리뷰를 제외하고는 이미지가 안 불러와짐 : 원인 불명
  - {{baseUrl}}/my/review/write 하면 2번째 리뷰부터 image가 nulll이다

## TODO

- [x] 유저 아이디로 리뷰를 선택
- [x] 여러 리뷰마다 이미지가 불러와지게 수정

**Comment by LeeJE20** [comment]
@choiyoorim 
첫 번쨰 리뷰를 제외하고는 이미지가 안 불러와지는 오류 해결부탁드려요~
제가 fix/my-review-#67 브랜치 만들어서 다른 것 조금 고쳤으니까 이 브랜치에서 문제상황 고치고 PR 해주세요~

**Comment by choiyoorim** [comment]
해당 이슈 수정했습니다~
