### ISSUE TITLE
[BUG] 리뷰 작성 안 됨

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#68]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- 로컬에서는 되는데 deploy에서 리뷰 포스트 하면 500 ERROR 발생
- 슬랙 API 안 붙어 있어서 에러 확인 안 됨

## TODO

- [x] 슬랙 API 붙여서 어떤 오류인지 확인해보기?
- [x] 어떻게든 고치기 -> review item id unique 값 중복 에러인듯
