### ISSUE TITLE
[FEATURE] [GET] /shop/:shopId api 제작

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#7]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- [GET] /shop/:shopId api 제작

## TODO

- [x] 라우팅 경로 설정
- [ ] 로그인 확인 미들웨어 붙이기
- [x] constants 작성
- [x] API 기본 틀 작성
- [x] ORM 작성
    + [x] db 라우팅 파일 작성 
    + [x] 샵 id에 해당하는 category 데이터 가져오기
    + [x] 샵 id에 해당하는 theme 데이터 가져오기
    + [x] 샵 id에 해당하는 이미지 가져오기 order by isPreview (이미지 배열에서 대표 이미지를 가장 앞에 두기)
    + [x] 샵 id에 해당하는 shop 가져오기
    + [x] 유저 id를 이용해 shop_bookmark 테이블에서 샵 id에 해당하는 북마크 있는지 확인
- [ ] API 내용 작성
    + [x] 필요한 모듈 require
    + [x] path variable 확인
    + [x] ORM 이용해서 shop 데이터 불러오기
    + [x] 실패 response: shop 데이터 결과 없으면 400
    + [x] ORM 이용해서 catogory, theme, image 불러오기
    + [ ] 로그인 했다면 북마크 여부 가져오기 (로그인 안하면 false)
    + [x] shop 데이터와 category, theme, image, 북마크 여부  합치기
    + [x] 성공 response 보내기
