### ISSUE TITLE
[BUG] 리뷰 상세페이지 response에 date 키 없음

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#74]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- GET {{baseUrl}}/shop/:shopId/review/:reviewId
- shopReviewIdGET.js 파일
- response에 date 키가 없음

## TODO

- [x] response에 date 키 넣기
