### ISSUE TITLE
[BUG] 스크랩, 좋아요 반영 안 되는 버그

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#75]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- 로그인 상태
- shopReviewIdGET.js
- GET {{baseUrl}}/shop/:shopId/review/:reviewId
- 리뷰를 스크랩을 해도 해당 리뷰 상세페이지에서 isScraped 안 뜸
- 리뷰를 좋아요 해도 해당 리뷰 상세페이지에서 isLiked 안 뜸

## TODO

- [x] 리뷰 상세페이지에서 isScraped 반영
- [x] 리뷰 상세페이지에서 isLiked 반영
