### ISSUE TITLE
[FEATURE] [GET] /shop/?theme api 제작 

### ISSUE THREAD

**Issue by Nahee-Park** [TeamSodam/sodam-server#8]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 테마별 소품샵 정보 제공 

## TODO

- [x] db로직 작성
- [x] db에서 받아온 데이터 js로 가공 (유틸로 빼기 ? 최대한 범용적으로 사용할 수 있는 틀 만들기 ) 
- [x] 쿼리 로직 작성 
- [x] 페이지네이션 구현
