### ISSUE TITLE
[BUG] 리뷰 상세페이지 item이 항상 들어가는 버그

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#82]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- 리뷰 상세페이지를 볼 때, 등록한 item이 없어도 항상 문구팬시 2900원 이하 데이터가 response에 들어있다
## TODO

- [ ] item 불러오는 부분 확인하고 response 수정
