### ISSUE TITLE
[REFACTOR] [GET] /shop/:shopId/review/:reviewId 테스트코드 작성, 리팩토링

### ISSUE THREAD

**Issue by Nahee-Park** [TeamSodam/sodam-server#88]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- [GET] /shop/:shopId/review/:reviewId 리팩토링

## TODO

- [x] 테스트 코드 작성 
- [x] 리팩토링
