### ISSUE TITLE
[REFACTOR] 지역별, 테마별 소품샵 정보 불러오기 테스트코드 작성

### ISSUE THREAD

**Issue by Nahee-Park** [TeamSodam/sodam-server#90]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- [GET] /shop?area={}&sort={} 테스트 코드 작성
- [GET] /shop?theme={}&sort={}&offset={}&limit={} 테스트 코드 작성

## TODO

- [x] [GET] /shop?area={}&sort={} 테스트 코드 작성
- [x]  [GET] /shop?area={}&sort={} 리팩토링
- [x] [GET] /shop?theme={}&sort={}&offset={}&limit={} 테스트 코드 작성
- [x]  [GET] /shop?theme={}&sort={}&offset={}&limit={}  리팩토링
