### ISSUE TITLE
[REFACTOR] 리뷰 좋아요, 스크랩 POST 테스트코드 작성, 리팩토링

### ISSUE THREAD

**Issue by Nahee-Park** [TeamSodam/sodam-server#92]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- [POST] /review/:reviewId/like 리팩토링
- [POST] /review/:reviewId/scrap 리팩토링

## TODO

- [x] [POST] /review/:reviewId/like 테스트코드 작성
- [x] [POST] /review/:reviewId/like 리팩토링
- [x] [POST] /review/:reviewId/scrap테스트코드 작성
- [x] [POST] /review/:reviewId/scrap 리팩토링
