### ISSUE TITLE
[REFACTOR] [GET] /shop/bookmark?sort={}&offset={}&limit={} 테스트코드 작성, 리팩토링

### ISSUE THREAD

**Issue by Nahee-Park** [TeamSodam/sodam-server#94]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- 저장한 소품샵 가져오기 api 리팩토링

## TODO

- [x] [GET] /shop/bookmark?sort={}&offset={}&limit={} 리팩토링
- [x] [GET] /shop/bookmark?sort={}&offset={}&limit={}  테스트코드 작성
