### ISSUE TITLE
[REFACTOR] [GET] /shop/recommend?type={} 테스트코드 작성, 리팩토링 

### ISSUE THREAD

**Issue by choiyoorim** [TeamSodam/sodam-server#96]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- 소품샵 추천(랜덤, 인기순) api 리팩토링

## TODO

- [x] [GET] /shop/recommed?type={} 리팩토링
- [x] [GET] /shop/recommed?type={} 테스트 코드 작성
