### ISSUE TITLE
[REFACTOR] [GET] /shop/:shopId 테스트코드 작성, 리팩토링

### ISSUE THREAD

**Issue by LeeJE20** [TeamSodam/sodam-server#98]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- 테스트코드 작성
- 리팩토링

## TODO

- [x] 테스트 코드 작성
  - [x] 정상적인 경우
  - [x] path variable이 잘못된 경우 (1 이상이 정수가 아닌 경우)
  - [x] shopId에 해당하는 샵의 데이터가 없는 경우
- [x] 리팩토링
  - [x] 주석 (필요한 경우)
  - [x] 효율성 개선
  - [x] 변수명 개선
  - [x] orm 살펴보기
